# Generated by Django 3.2 on 2023-10-12 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Data Table ',
                'ordering': ['no'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('name', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='image_tauthong')),
            ],
            options={
                'verbose_name': 'Round',
                'verbose_name_plural': 'Round Table ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Round_Tauthong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('check', models.BooleanField(blank=True, default=True, null=True)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lucky_random_Number.data')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lucky_random_Number.round')),
            ],
            options={
                'verbose_name': 'Round',
                'verbose_name_plural': 'Round Tauthong',
                'ordering': ['number'],
            },
        ),
    ]
