# Generated by Django 3.2 on 2023-10-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_random_Number', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round_tauthong',
            name='number',
            field=models.CharField(max_length=4),
        ),
    ]
