# Generated by Django 3.2 on 2023-10-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_random_Number', '0002_alter_round_tauthong_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='id',
        ),
        migrations.AlterField(
            model_name='data',
            name='no',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
