# Generated by Django 3.2 on 2023-10-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_random_Number', '0003_auto_20231012_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='image_tauthong'),
        ),
    ]
