# Generated by Django 3.2 on 2023-10-12 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv', models.CharField(choices=[('lv1', 'Lv1'), ('lv2', 'Lv2'), ('lv3', 'Lv3'), ('lv4', 'Lv4'), ('lv5', 'Lv5')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('contact', models.CharField(choices=[('Line', 'Line'), ('Facebook', 'Facebook'), ('Phone', 'Phone'), ('Telegram', 'Telegram'), ('etc.', 'Etc.')], max_length=10)),
                ('notice', models.CharField(max_length=255)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.permission')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
